"""Delivery/marketplace orders, integrations and product mappings.

Written by hand rather than autogenerated: autogenerate also wanted to strip
server defaults that earlier migrations deliberately set, which is exactly the
drift that broke a fresh install once already.

Revision ID: 0022_delivery_orders
Revises: 0021_onboarding_payments
Create Date: 2026-08-10
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "0022_delivery_orders"
down_revision = "0021_onboarding_payments"
branch_labels = None
depends_on = None

DELIVERY = "delivery_orders"
INTEGRATIONS = "marketplace_integrations"
MAPPINGS = "marketplace_product_mappings"


def _timestamps() -> list[sa.Column]:
    return [
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    ]


def upgrade() -> None:
    bind = op.get_bind()
    tables = set(sa.inspect(bind).get_table_names())

    if DELIVERY not in tables:
        op.create_table(
            DELIVERY,
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("tenant_id", sa.Uuid(), nullable=False),
            sa.Column("branch_id", sa.Uuid(), nullable=False),
            sa.Column("order_id", sa.Uuid(), nullable=False),
            sa.Column("channel", sa.String(30), nullable=False),
            sa.Column("provider", sa.String(30), nullable=True),
            sa.Column(
                "delivery_status", sa.String(30), nullable=False, server_default="NEW"
            ),
            sa.Column("external_order_id", sa.String(120), nullable=True),
            sa.Column("external_display_id", sa.String(60), nullable=True),
            sa.Column("external_status", sa.String(60), nullable=True),
            sa.Column("external_created_at", sa.DateTime(), nullable=True),
            sa.Column(
                "sync_status",
                sa.String(30),
                nullable=False,
                server_default="NOT_APPLICABLE",
            ),
            sa.Column("sync_error", sa.String(500), nullable=True),
            sa.Column("last_synced_at", sa.DateTime(), nullable=True),
            sa.Column("customer_name", sa.String(160), nullable=True),
            sa.Column("customer_phone", sa.String(32), nullable=True),
            sa.Column("address_line", sa.Text(), nullable=True),
            sa.Column("district", sa.String(120), nullable=True),
            sa.Column("neighbourhood", sa.String(120), nullable=True),
            sa.Column("address_note", sa.Text(), nullable=True),
            sa.Column("customer_note", sa.Text(), nullable=True),
            sa.Column(
                "payment_method",
                sa.String(30),
                nullable=False,
                server_default="CASH_ON_DELIVERY",
            ),
            sa.Column(
                "payment_status", sa.String(30), nullable=False, server_default="UNPAID"
            ),
            sa.Column("delivery_fee", sa.Numeric(14, 2), nullable=True),
            sa.Column("provider_discount", sa.Numeric(14, 2), nullable=True),
            sa.Column("restaurant_discount", sa.Numeric(14, 2), nullable=True),
            sa.Column("provider_commission", sa.Numeric(14, 2), nullable=True),
            sa.Column("net_expected_amount", sa.Numeric(14, 2), nullable=True),
            sa.Column("courier_user_id", sa.Uuid(), nullable=True),
            sa.Column("courier_name", sa.String(160), nullable=True),
            sa.Column("promised_minutes", sa.Integer(), nullable=True),
            sa.Column("accepted_at", sa.DateTime(), nullable=True),
            sa.Column("ready_at", sa.DateTime(), nullable=True),
            sa.Column("dispatched_at", sa.DateTime(), nullable=True),
            sa.Column("delivered_at", sa.DateTime(), nullable=True),
            sa.Column("cancelled_at", sa.DateTime(), nullable=True),
            sa.Column("rejection_reason", sa.String(255), nullable=True),
            *_timestamps(),
            sa.ForeignKeyConstraint(
                ["tenant_id"], ["tenants.id"], name=f"fk_{DELIVERY}_tenant"
            ),
            sa.ForeignKeyConstraint(
                ["branch_id"], ["branches.id"], name=f"fk_{DELIVERY}_branch"
            ),
            sa.ForeignKeyConstraint(
                ["order_id"], ["orders.id"], name=f"fk_{DELIVERY}_order"
            ),
            sa.ForeignKeyConstraint(
                ["courier_user_id"],
                ["users.id"],
                name=f"fk_{DELIVERY}_courier",
                ondelete="SET NULL",
            ),
            sa.PrimaryKeyConstraint("id", name=f"pk_{DELIVERY}"),
            sa.UniqueConstraint("order_id", name="uq_delivery_order_order"),
            # Idempotency: one external order can only ever become one Dixora order.
            sa.UniqueConstraint(
                "tenant_id",
                "provider",
                "external_order_id",
                name="uq_delivery_order_external",
            ),
        )
        op.create_index(f"ix_{DELIVERY}_tenant_id", DELIVERY, ["tenant_id"])
        op.create_index(f"ix_{DELIVERY}_branch_id", DELIVERY, ["branch_id"])
        op.create_index(f"ix_{DELIVERY}_order_id", DELIVERY, ["order_id"])
        op.create_index(f"ix_{DELIVERY}_delivery_status", DELIVERY, ["delivery_status"])
        op.create_index(f"ix_{DELIVERY}_courier_user_id", DELIVERY, ["courier_user_id"])
        # Drives the operational inbox query.
        op.create_index(
            "ix_delivery_orders_inbox",
            DELIVERY,
            ["tenant_id", "branch_id", "delivery_status", "created_at"],
        )
        op.create_index(
            "ix_delivery_orders_channel",
            DELIVERY,
            ["tenant_id", "branch_id", "channel"],
        )

    if INTEGRATIONS not in tables:
        op.create_table(
            INTEGRATIONS,
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("tenant_id", sa.Uuid(), nullable=False),
            sa.Column("branch_id", sa.Uuid(), nullable=False),
            sa.Column("provider", sa.String(30), nullable=False),
            sa.Column(
                "is_enabled", sa.Boolean(), nullable=False, server_default=sa.false()
            ),
            sa.Column("external_store_id", sa.String(120), nullable=True),
            sa.Column("credential_ref", sa.String(200), nullable=True),
            sa.Column("settings", sa.JSON(), nullable=False, server_default="{}"),
            sa.Column("last_sync_at", sa.DateTime(), nullable=True),
            sa.Column("last_error", sa.String(500), nullable=True),
            sa.Column("last_error_at", sa.DateTime(), nullable=True),
            *_timestamps(),
            sa.ForeignKeyConstraint(
                ["tenant_id"],
                ["tenants.id"],
                name=f"fk_{INTEGRATIONS}_tenant",
                ondelete="CASCADE",
            ),
            sa.ForeignKeyConstraint(
                ["branch_id"],
                ["branches.id"],
                name=f"fk_{INTEGRATIONS}_branch",
                ondelete="CASCADE",
            ),
            sa.PrimaryKeyConstraint("id", name=f"pk_{INTEGRATIONS}"),
            sa.UniqueConstraint(
                "tenant_id",
                "branch_id",
                "provider",
                name="uq_marketplace_integration_scope",
            ),
        )
        op.create_index(f"ix_{INTEGRATIONS}_tenant_id", INTEGRATIONS, ["tenant_id"])
        op.create_index(f"ix_{INTEGRATIONS}_branch_id", INTEGRATIONS, ["branch_id"])

    if MAPPINGS not in tables:
        op.create_table(
            MAPPINGS,
            sa.Column("id", sa.Uuid(), nullable=False),
            sa.Column("tenant_id", sa.Uuid(), nullable=False),
            sa.Column("branch_id", sa.Uuid(), nullable=False),
            sa.Column("provider", sa.String(30), nullable=False),
            sa.Column("product_id", sa.Uuid(), nullable=False),
            sa.Column("external_product_id", sa.String(120), nullable=False),
            sa.Column("external_name", sa.String(200), nullable=True),
            sa.Column(
                "sync_status",
                sa.String(30),
                nullable=False,
                server_default="NOT_APPLICABLE",
            ),
            sa.Column("last_synced_at", sa.DateTime(), nullable=True),
            *_timestamps(),
            sa.ForeignKeyConstraint(
                ["tenant_id"],
                ["tenants.id"],
                name=f"fk_{MAPPINGS}_tenant",
                ondelete="CASCADE",
            ),
            sa.ForeignKeyConstraint(
                ["branch_id"],
                ["branches.id"],
                name=f"fk_{MAPPINGS}_branch",
                ondelete="CASCADE",
            ),
            sa.ForeignKeyConstraint(
                ["product_id"],
                ["products.id"],
                name=f"fk_{MAPPINGS}_product",
                ondelete="CASCADE",
            ),
            sa.PrimaryKeyConstraint("id", name=f"pk_{MAPPINGS}"),
            sa.UniqueConstraint(
                "tenant_id",
                "branch_id",
                "provider",
                "product_id",
                name="uq_marketplace_mapping_product",
            ),
            sa.UniqueConstraint(
                "tenant_id",
                "branch_id",
                "provider",
                "external_product_id",
                name="uq_marketplace_mapping_external",
            ),
        )
        op.create_index(f"ix_{MAPPINGS}_tenant_id", MAPPINGS, ["tenant_id"])
        op.create_index(f"ix_{MAPPINGS}_branch_id", MAPPINGS, ["branch_id"])
        op.create_index(f"ix_{MAPPINGS}_product_id", MAPPINGS, ["product_id"])


def downgrade() -> None:
    bind = op.get_bind()
    tables = set(sa.inspect(bind).get_table_names())
    for name in (MAPPINGS, INTEGRATIONS, DELIVERY):
        if name in tables:
            op.drop_table(name)
